import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { format } from 'date-fns'
import ReportPageShell from '../ReportPageShell'

// AttachmentsSection fetches its own data; the shell only decides whether and how it is mounted
vi.mock('../../AttachmentsSection', () => ({
  default: (props) => (
    <div data-testid="attachments-section" data-idr={props.idrId} data-report={props.reportId}
      data-submitted={String(props.isSubmitted)} />
  ),
}))

const SUBMITTED_AT = '2026-09-25T15:10:00Z'

// A ready, editable form as useReportForm returns it; override per test
function formState(overrides = {}) {
  return {
    idrId: 'idr-1',
    reportId: 'rep-1',
    loadStatus: 'ready',
    loadError: null,
    retryLoad: vi.fn(),
    idr: { report_date: '2026-09-27', weather_am: 'Clear', weather_pm: 'Cloudy', temp_low: 42, temp_high: 61,
      work_start_time: '07:30:00', work_end_time: '16:00:00' },
    project: { project_id: 'HWS0023', registration_code: '2024123457', project_description: 'Curbs and ramps',
      borough: 'Queens' },
    submittedAt: null,
    saveStatus: 'idle',
    savedAt: null,
    saveError: null,
    hasUnsavedChanges: false,
    handleSaveDraft: vi.fn(),
    refreshError: null,
    conflictMessage: null,
    refresh: vi.fn(),
    reloadAfterConflict: vi.fn(),
    isLocked: false,
    isReadOnly: false,
    isAutoGenerated: false,
    backToIdr: vi.fn(),
    backToProject: vi.fn(),
    ...overrides,
  }
}

function renderShell(overrides = {}, props = {}) {
  const form = formState(overrides)
  render(
    <ReportPageShell title="Test Inspector's Report" form={form} {...props}>
      <input aria-label="Body field" />
    </ReportPageShell>
  )
  return form
}

const saveButtons = () => screen.queryAllByRole('button', { name: /save draft/i })

describe('ReportPageShell', () => {
  it('shows only a spinner while loading', () => {
    renderShell({ loadStatus: 'loading', project: null, idr: null })
    expect(screen.getByRole('status')).toBeInTheDocument()
    expect(screen.queryByLabelText('Body field')).not.toBeInTheDocument()
  })

  it('shows the load error with Retry and Back to IDR', async () => {
    const form = renderShell({ loadStatus: 'error', loadError: 'IDR not found', project: null, idr: null })
    expect(screen.getByText('IDR not found')).toBeInTheDocument()
    expect(screen.queryByLabelText('Body field')).not.toBeInTheDocument()
    const user = userEvent.setup()
    await user.click(screen.getByRole('button', { name: 'Retry' }))
    expect(form.retryLoad).toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: 'Back to IDR' }))
    expect(form.backToIdr).toHaveBeenCalled()
  })

  it('renders the title, project card, IDR context line and the page body', () => {
    renderShell()
    expect(screen.getByRole('heading', { name: "Test Inspector's Report" })).toBeInTheDocument()
    expect(screen.getByText('Contract No:').parentElement).toHaveTextContent('HWS0023')
    expect(screen.getByText('Reg. No:').parentElement).toHaveTextContent('2024123457')
    expect(screen.getByText('Borough:').parentElement).toHaveTextContent('Queens')
    expect(screen.getByText(/Set on the IDR page/)).toBeInTheDocument()
    expect(screen.getByLabelText('Body field')).toBeEnabled()
  })

  it('has Save Draft in the header and footer, and wires Back to IDR, Cancel and Save Draft', async () => {
    const form = renderShell({ hasUnsavedChanges: true })
    expect(saveButtons()).toHaveLength(2)
    expect(screen.getByText(/unsaved changes/i)).toBeInTheDocument()
    const user = userEvent.setup()
    await user.click(saveButtons()[1])
    expect(form.handleSaveDraft).toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: 'Back to IDR' }))
    expect(form.backToIdr).toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(form.backToProject).toHaveBeenCalled()
  })

  it('mounts attachments for this report, editable on a draft', () => {
    renderShell()
    const attachments = screen.getByTestId('attachments-section')
    expect(attachments).toHaveAttribute('data-idr', 'idr-1')
    expect(attachments).toHaveAttribute('data-report', 'rep-1')
    expect(attachments).toHaveAttribute('data-submitted', 'false')
  })

  it('when locked: submitted banner, disabled body, no Save Draft, view-only attachments', () => {
    renderShell({ isLocked: true, isReadOnly: true, submittedAt: SUBMITTED_AT })
    expect(screen.getByText(
      `This report belongs to an IDR that was submitted at ${format(new Date(SUBMITTED_AT), "HH:mm 'on' MMMM d, yyyy")}`
    )).toBeInTheDocument()
    expect(screen.getByLabelText('Body field')).toBeDisabled()
    expect(saveButtons()).toHaveLength(0)
    expect(screen.getByRole('button', { name: 'Cancel' })).toBeInTheDocument()
    expect(screen.getByTestId('attachments-section')).toHaveAttribute('data-submitted', 'true')
  })

  it('when auto-generated: shows the banner text, disables the body, hides Save Draft and attachments', () => {
    renderShell({ isAutoGenerated: true, isReadOnly: true }, { autoGeneratedBannerText: 'Built from your other reports.' })
    expect(screen.getByText('Built from your other reports.')).toBeInTheDocument()
    expect(screen.getByLabelText('Body field')).toBeDisabled()
    expect(saveButtons()).toHaveLength(0)
    expect(screen.queryByTestId('attachments-section')).not.toBeInTheDocument()
  })

  it('hides the auto-generated banner once the IDR is submitted', () => {
    renderShell(
      { isAutoGenerated: true, isLocked: true, isReadOnly: true, submittedAt: SUBMITTED_AT },
      { autoGeneratedBannerText: 'Built from your other reports.' }
    )
    expect(screen.queryByText('Built from your other reports.')).not.toBeInTheDocument()
  })

  it('shows the conflict message, and a refresh error whose Retry reloads after a conflict', async () => {
    const form = renderShell({ conflictMessage: 'Submitted while you were editing.', refreshError: 'Network error' })
    expect(screen.getByText('Submitted while you were editing.')).toBeInTheDocument()
    expect(screen.getByText("Couldn't refresh this IDR: Network error")).toBeInTheDocument()
    await userEvent.setup().click(screen.getByRole('button', { name: 'Retry' }))
    expect(form.reloadAfterConflict).toHaveBeenCalled()
    expect(form.refresh).not.toHaveBeenCalled()
  })

  it("a refresh error's Retry refetches when there was no conflict", async () => {
    const form = renderShell({ refreshError: 'Network error' })
    await userEvent.setup().click(screen.getByRole('button', { name: 'Retry' }))
    expect(form.refresh).toHaveBeenCalled()
  })
})
