import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { format } from 'date-fns'
import ReportPageShell from '../ReportPageShell'
import { LeaveGuardProvider, useGuardedLeave } from '../../../contexts/LeaveGuardContext'

// AttachmentsSection fetches its own data; the shell only decides whether and how it is mounted
vi.mock('../../AttachmentsSection', () => ({
  default: (props) => (
    <div data-testid="attachments-section" data-idr={props.idrId} data-report={props.reportId}
      data-submitted={String(props.isSubmitted)} />
  ),
}))

// AddendumsSection navigates and calls the API itself; the shell only decides whether and how it is mounted
vi.mock('../AddendumsSection', () => ({
  default: (props) => (
    <div data-testid="addendums-section" data-project={props.projectId} data-idr={props.idrId}
      data-report={props.reportId} data-count={props.reports.length} data-disabled={String(props.disabled)}
      data-safe-nav={String(typeof props.navigateSafely === 'function')}
      onClick={props.onChanged} />
  ),
}))

const SUBMITTED_AT = '2026-09-25T15:10:00Z'

// A ready, editable form as useReportForm returns it; override per test
function formState(overrides = {}) {
  return {
    projectId: 'HWS0023',
    idrId: 'idr-1',
    reportId: 'rep-1',
    reports: [
      { report_id: 'rep-1', report_type: 'SWCB', is_addendum: false, parent_report_id: null },
      { report_id: 'rep-2', report_type: 'CONC_MIX', is_addendum: true, parent_report_id: 'rep-1' },
    ],
    report: { report_id: 'rep-1', report_type: 'SWCB', is_addendum: false, parent_report_id: null },
    loadStatus: 'ready',
    loadError: null,
    retryLoad: vi.fn(),
    idr: { report_date: '2026-09-27', weather_am: 'Clear', weather_pm: 'Cloudy', temp_low: 42, temp_high: 61,
      work_start_time: '07:30:00', work_end_time: '16:00:00' },
    project: { project_id: 'HWS0023', registration_code: '2024123457', project_description: 'Curbs and ramps',
      borough: 'Queens' },
    submittedAt: null,
    saveStatus: 'idle',
    savedAt: null,
    saveError: null,
    hasUnsavedChanges: false,
    handleSaveDraft: vi.fn(),
    refreshError: null,
    conflictMessage: null,
    refresh: vi.fn(),
    reloadAfterConflict: vi.fn(),
    isLocked: false,
    isReadOnly: false,
    isAutoGenerated: false,
    backToIdr: vi.fn(),
    backToProject: vi.fn(),
    navigateSafely: vi.fn(),
    ...overrides,
  }
}

function renderShell(overrides = {}, props = {}) {
  const form = formState(overrides)
  render(
    <ReportPageShell title="Test Inspector's Report" form={form} {...props}>
      <input aria-label="Body field" />
    </ReportPageShell>
  )
  return form
}

const saveButtons = () => screen.queryAllByRole('button', { name: /save draft/i })

describe('ReportPageShell', () => {
  it('shows only a spinner while loading', () => {
    renderShell({ loadStatus: 'loading', project: null, idr: null })
    expect(screen.getByRole('status')).toBeInTheDocument()
    expect(screen.queryByLabelText('Body field')).not.toBeInTheDocument()
  })

  it('shows the load error with Retry and Back to IDR', async () => {
    const form = renderShell({ loadStatus: 'error', loadError: 'IDR not found', project: null, idr: null })
    expect(screen.getByText('IDR not found')).toBeInTheDocument()
    expect(screen.queryByLabelText('Body field')).not.toBeInTheDocument()
    const user = userEvent.setup()
    await user.click(screen.getByRole('button', { name: 'Retry' }))
    expect(form.retryLoad).toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: 'Back to IDR' }))
    expect(form.backToIdr).toHaveBeenCalled()
  })

  it('renders the title, project card, IDR context line and the page body', () => {
    renderShell()
    expect(screen.getByRole('heading', { name: "Test Inspector's Report" })).toBeInTheDocument()
    expect(screen.getByText('Contract No:').parentElement).toHaveTextContent('HWS0023')
    expect(screen.getByText('Reg. No:').parentElement).toHaveTextContent('2024123457')
    expect(screen.getByText('Borough:').parentElement).toHaveTextContent('Queens')
    expect(screen.getByText(/Set on the IDR page/)).toBeInTheDocument()
    expect(screen.getByLabelText('Body field')).toBeEnabled()
  })

  it('has Save Draft in the header and footer', async () => {
    const form = renderShell({ hasUnsavedChanges: true })
    expect(saveButtons()).toHaveLength(2)
    expect(screen.getByText(/unsaved changes/i)).toBeInTheDocument()
    await userEvent.setup().click(saveButtons()[1])
    expect(form.handleSaveDraft).toHaveBeenCalled()
  })

  it('sends Back to IDR and Cancel through navigateSafely (which saves unsaved edits first)', async () => {
    const form = renderShell({ hasUnsavedChanges: true })
    const user = userEvent.setup()
    await user.click(screen.getByRole('button', { name: 'Back to IDR' }))
    expect(form.navigateSafely).toHaveBeenLastCalledWith(form.backToIdr)
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(form.navigateSafely).toHaveBeenLastCalledWith(form.backToProject)
    form.navigateSafely.mockClear()
    await user.click(screen.getByRole('button', { name: 'Go to Project Page' }))
    expect(form.navigateSafely).toHaveBeenCalledTimes(1)
    expect(form.navigateSafely).toHaveBeenLastCalledWith(form.backToProject)
    // The shell never navigates around navigateSafely
    expect(form.backToIdr).not.toHaveBeenCalled()
    expect(form.backToProject).not.toHaveBeenCalled()
  })

  it('passes navigateSafely to the addendums section', () => {
    renderShell()
    expect(screen.getByTestId('addendums-section')).toHaveAttribute('data-safe-nav', 'true')
  })

  it('mounts attachments for this report, editable on a draft', () => {
    renderShell()
    const attachments = screen.getByTestId('attachments-section')
    expect(attachments).toHaveAttribute('data-idr', 'idr-1')
    expect(attachments).toHaveAttribute('data-report', 'rep-1')
    expect(attachments).toHaveAttribute('data-submitted', 'false')
  })

  it("mounts addendums on a main report, with the IDR's reports, enabled on a draft", async () => {
    const form = renderShell()
    const addendums = screen.getByTestId('addendums-section')
    expect(addendums).toHaveAttribute('data-project', 'HWS0023')
    expect(addendums).toHaveAttribute('data-idr', 'idr-1')
    expect(addendums).toHaveAttribute('data-report', 'rep-1')
    expect(addendums).toHaveAttribute('data-count', '2')
    expect(addendums).toHaveAttribute('data-disabled', 'false')
    await userEvent.setup().click(addendums)
    expect(form.refresh).toHaveBeenCalled() // onChanged refetches the IDR
  })

  it('shows no addendums section on an addendum (an addendum cannot have addendums)', () => {
    renderShell({ report: { report_id: 'rep-2', report_type: 'CONC_MIX', is_addendum: true, parent_report_id: 'rep-1' } })
    expect(screen.queryByTestId('addendums-section')).not.toBeInTheDocument()
    expect(screen.getByTestId('attachments-section')).toBeInTheDocument()
  })

  it('when locked: submitted banner, disabled body, no Save Draft, view-only attachments', () => {
    renderShell({ isLocked: true, isReadOnly: true, submittedAt: SUBMITTED_AT })
    expect(screen.getByText(
      `This report belongs to an IDR that was submitted at ${format(new Date(SUBMITTED_AT), "HH:mm 'on' MMMM d, yyyy")}`
    )).toBeInTheDocument()
    expect(screen.getByLabelText('Body field')).toBeDisabled()
    expect(saveButtons()).toHaveLength(0)
    expect(screen.getByRole('button', { name: 'Cancel' })).toBeInTheDocument()
    expect(screen.getByTestId('attachments-section')).toHaveAttribute('data-submitted', 'true')
    expect(screen.getByTestId('addendums-section')).toHaveAttribute('data-disabled', 'true')
  })

  it('when auto-generated: shows the banner text, disables the body, hides Save Draft and attachments', () => {
    renderShell({ isAutoGenerated: true, isReadOnly: true }, { autoGeneratedBannerText: 'Built from your other reports.' })
    expect(screen.getByText('Built from your other reports.')).toBeInTheDocument()
    expect(screen.getByLabelText('Body field')).toBeDisabled()
    expect(saveButtons()).toHaveLength(0)
    expect(screen.queryByTestId('attachments-section')).not.toBeInTheDocument()
    expect(screen.getByTestId('addendums-section')).toHaveAttribute('data-disabled', 'true')
  })

  it('hides the auto-generated banner once the IDR is submitted', () => {
    renderShell(
      { isAutoGenerated: true, isLocked: true, isReadOnly: true, submittedAt: SUBMITTED_AT },
      { autoGeneratedBannerText: 'Built from your other reports.' }
    )
    expect(screen.queryByText('Built from your other reports.')).not.toBeInTheDocument()
  })

  it('shows the conflict message, and a refresh error whose Retry reloads after a conflict', async () => {
    const form = renderShell({ conflictMessage: 'Submitted while you were editing.', refreshError: 'Network error' })
    expect(screen.getByText('Submitted while you were editing.')).toBeInTheDocument()
    expect(screen.getByText("Couldn't refresh this IDR: Network error")).toBeInTheDocument()
    await userEvent.setup().click(screen.getByRole('button', { name: 'Retry' }))
    expect(form.reloadAfterConflict).toHaveBeenCalled()
    expect(form.refresh).not.toHaveBeenCalled()
  })

  it("a refresh error's Retry refetches when there was no conflict", async () => {
    const form = renderShell({ refreshError: 'Network error' })
    await userEvent.setup().click(screen.getByRole('button', { name: 'Retry' }))
    expect(form.refresh).toHaveBeenCalled()
  })
})

describe('ReportPageShell — Go to Project Page', () => {
  it('sits right after Back to IDR in the header', () => {
    renderShell()
    const back = screen.getByRole('button', { name: 'Back to IDR' })
    expect(back.nextElementSibling).toBe(screen.getByRole('button', { name: 'Go to Project Page' }))
  })

  it('is there on a submitted (read-only) report too', () => {
    renderShell({ isLocked: true, isReadOnly: true, submittedAt: SUBMITTED_AT })
    expect(screen.getByRole('button', { name: 'Go to Project Page' })).toBeEnabled()
  })
})

describe('ReportPageShell — leave guard for the app header', () => {
  // Stands in for the app header: an exit that isn't one of the shell's own buttons
  function HeaderExit({ action }) {
    const leave = useGuardedLeave()
    return <button onClick={() => leave(action)}>header exit</button>
  }

  it("routes the header's exits through navigateSafely, so unsaved edits are saved first", async () => {
    const form = formState({ hasUnsavedChanges: true })
    const action = vi.fn()
    render(
      <LeaveGuardProvider>
        <HeaderExit action={action} />
        <ReportPageShell title="SWCB Report" form={form}><div /></ReportPageShell>
      </LeaveGuardProvider>
    )
    await userEvent.setup().click(screen.getByRole('button', { name: 'header exit' }))
    expect(form.navigateSafely).toHaveBeenCalledTimes(1)
    expect(form.navigateSafely).toHaveBeenCalledWith(action)
    expect(action).not.toHaveBeenCalled() // navigateSafely decides, here a mock that never runs it
  })
})
