/**
 * Form management shared by the report pages: loads the parent IDR and project, picks this page's report out of the
 * IDR (throwing a readable error when it's missing or the wrong type), keeps the form state with unsaved-change
 * tracking, and saves drafts (refetching the IDR after, reloading read-only on a 409 when the IDR was submitted).
 * Alongside the IDR it fetches the project's contract items for the pay-item picker; that failing never blocks the form.
 * Takes { idrId, projectId, reportId, expectedReportType, emptyFormData, formDataFromReport(reportData, defaults),
 * isAutoGenType }. Returns the form state, load / save / IDR state (including all the IDR's reports and this report's
 * row), the project's contract items with their load state, derived read-only flags, the handlers for the sections every report shares, and navigation helpers.
 */
import { useCallback, useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { getContractItems, getIdr, getProjectById, saveReport } from '../services/api'
import { reportTypeLabel } from '../data/reportTypes'

export const SUBMITTED_MID_EDIT =
  'This IDR was submitted while you were editing. Your unsaved changes could not be saved. Reloading...'

// Picks this page's report out of a getIdr response; throws the message to show when it can't be opened here
function findReport(idr, projectId, reportId, expectedReportType) {
  if (idr.project_id !== projectId) throw new Error('IDR not found in this project')
  const report = idr.reports.find(r => r.report_id === reportId)
  if (!report) throw new Error('Report not found in this IDR')
  if (report.report_type !== expectedReportType) {
    const label = reportTypeLabel(expectedReportType)
    const article = /^[aeiou]/i.test(label.trim()) ? 'an' : 'a'
    throw new Error(`This report is not ${article} ${label} report`)
  }
  return report
}

export default function useReportForm({
  idrId,
  projectId,
  reportId,
  expectedReportType,
  emptyFormData,
  formDataFromReport,
  isAutoGenType = false,
}) {
  const navigate = useNavigate()
  const location = useLocation()
  // Carry the list the IDR was opened from, so the IDR page's own Back still goes there
  const backToIdr = () => navigate(`/project/${projectId}/idr/${idrId}`, { state: { from: location.state?.from } })
  const backToProject = () => navigate(`/project/${projectId}`)

  // The page's form functions, read through a ref so a page passing new function instances can't retrigger the load
  const formFns = useRef({ emptyFormData, formDataFromReport })
  formFns.current = { emptyFormData, formDataFromReport }

  // Draft save state
  const [saveStatus, setSaveStatus] = useState('idle') // 'idle' | 'saving' | 'saved' | 'error'
  const [savedAt, setSavedAt] = useState(null)
  const [saveError, setSaveError] = useState(null)
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false)
  const savingRef = useRef(false)
  const editCountRef = useRef(0) // bumps on every edit; lets a finished save tell if edits happened mid-flight

  // Loading the parent IDR (spinner on first load only; refetches after a save are silent)
  const [loadStatus, setLoadStatus] = useState('loading') // 'loading' | 'ready' | 'error'
  const [loadError, setLoadError] = useState(null)
  const [loadAttempt, setLoadAttempt] = useState(0) // bump to retry
  const [idr, setIdr] = useState(null) // the parent IDR without its reports (status, date, weather, times)
  const [reports, setReports] = useState([]) // every report in the parent IDR, as of the last fetch (for addendums)
  const [project, setProject] = useState(null) // the project card's details, loaded with the IDR
  const [idrStatus, setIdrStatus] = useState('draft')
  const [submittedAt, setSubmittedAt] = useState(null)
  const [refreshError, setRefreshError] = useState(null)
  const [conflictMessage, setConflictMessage] = useState(null) // set when a save hit an already-submitted IDR

  // The project's contract items, for picking pay items. Fetched once per mount, independently of the IDR load.
  const [contractItems, setContractItems] = useState([])
  const [contractItemsLoading, setContractItemsLoading] = useState(true)
  const [contractItemsError, setContractItemsError] = useState(null)

  const [formData, setFormData] = useState(emptyFormData)
  const [isAutoGenerated, setIsAutoGenerated] = useState(false) // this report is a backend-built General

  // IDR-level state only. A refetch never touches the form, so it can't overwrite typing.
  const applyIdr = useCallback(({ reports, ...idrFields }) => {
    setIdr(idrFields)
    setReports(reports)
    setIdrStatus(idrFields.status)
    setSubmittedAt(idrFields.submitted_at ?? null)
  }, [])

  // Replaces the form with this report's saved data (first load, retry, and the reload after a 409)
  const loadForm = useCallback((idr) => {
    const report = findReport(idr, projectId, reportId, expectedReportType)
    applyIdr(idr)
    const { emptyFormData, formDataFromReport } = formFns.current
    setFormData(formDataFromReport(report.report_data, emptyFormData()))
    setIsAutoGenerated(isAutoGenType && report.is_auto_generated === true)
    setHasUnsavedChanges(false)
    setSaveStatus('idle')
    setSavedAt(null)
    setSaveError(null)
  }, [projectId, reportId, expectedReportType, isAutoGenType, applyIdr])

  useEffect(() => {
    let ignore = false
    setLoadStatus('loading')
    setLoadError(null)
    Promise.all([getIdr(idrId), getProjectById(projectId)])
      .then(([idr, project]) => {
        if (ignore) return
        loadForm(idr)
        setProject(project)
        setLoadStatus('ready')
      })
      .catch(err => {
        if (ignore) return
        setLoadError(err.message)
        setLoadStatus('error')
      })
    return () => { ignore = true }
  }, [idrId, projectId, loadAttempt, loadForm])

  const retryLoad = () => setLoadAttempt(a => a + 1)

  // A failure is only logged and recorded: the form loads regardless, and pay items fall back to manual entry
  useEffect(() => {
    let ignore = false
    setContractItemsLoading(true)
    setContractItemsError(null)
    getContractItems(projectId)
      .then(items => {
        if (ignore) return
        setContractItems(items)
      })
      .catch(err => {
        if (ignore) return
        console.error('Failed to load contract items:', err)
        setContractItemsError(err.message)
      })
      .finally(() => {
        if (!ignore) setContractItemsLoading(false)
      })
    return () => { ignore = true }
  }, [projectId])

  // Every form edit goes through here so unsaved-change tracking can't be skipped.
  const updateForm = (updater) => {
    setFormData(updater)
    editCountRef.current += 1
    setHasUnsavedChanges(true)
  }

  // Handlers for the sections every report shares

  const handleInputChange = (field, value) => {
    updateForm(prev => ({ ...prev, [field]: value }))
  }

  const handleNestedInputChange = (parent, field, value) => {
    updateForm(prev => ({
      ...prev,
      [parent]: {
        ...prev[parent],
        [field]: value
      }
    }))
  }

  const handleSafetyCheckChange = (field, value) => {
    updateForm(prev => ({
      ...prev,
      safetyChecks: {
        ...prev.safetyChecks,
        [field]: value
      }
    }))
  }

  const handleSafetyRemarksChange = (key, value) => {
    updateForm(prev => ({
      ...prev,
      safetyRemarks: {
        ...prev.safetyRemarks,
        [key]: value
      }
    }))
  }

  const addPayItem = () => {
    updateForm(prev => ({
      ...prev,
      payItems: [...prev.payItems, { itemNo: '', budgetCode: '', payQuantity: '', unit: '', description: '' }]
    }))
  }

  const removePayItem = (index) => {
    updateForm(prev => ({ ...prev, payItems: prev.payItems.filter((_, i) => i !== index) }))
  }

  const handlePayItemChange = (index, field, value) => {
    updateForm(prev => ({
      ...prev,
      payItems: prev.payItems.map((item, i) => (i === index ? { ...item, [field]: value } : item))
    }))
  }

  // Trades added beyond the default workforce roles
  const handleAddTrade = (label) => {
    updateForm(prev => ({ ...prev, additionalWorkforce: [...prev.additionalWorkforce, { label, count: '' }] }))
  }

  const handleChangeAdditionalWorkforce = (index, field, value) => {
    updateForm(prev => ({
      ...prev,
      additionalWorkforce: prev.additionalWorkforce.map((row, i) => (i === index ? { ...row, [field]: value } : row))
    }))
  }

  const handleRemoveAdditionalWorkforce = (index) => {
    updateForm(prev => ({ ...prev, additionalWorkforce: prev.additionalWorkforce.filter((_, i) => i !== index) }))
  }

  // Equipment added beyond the default types
  const handleAddEquipment = (label) => {
    updateForm(prev => ({ ...prev, additionalEquipment: [...prev.additionalEquipment, { label, model: '', number: '' }] }))
  }

  const handleChangeAdditionalEquipment = (index, field, value) => {
    updateForm(prev => ({
      ...prev,
      additionalEquipment: prev.additionalEquipment.map((row, i) => (i === index ? { ...row, [field]: value } : row))
    }))
  }

  const handleRemoveAdditionalEquipment = (index) => {
    updateForm(prev => ({ ...prev, additionalEquipment: prev.additionalEquipment.filter((_, i) => i !== index) }))
  }

  // Silent refetch: keeps the IDR's status fresh (and the drafts list order, via its updated_at bump)
  const refresh = async () => {
    try {
      applyIdr(await getIdr(idrId))
      setRefreshError(null)
    } catch (err) {
      setRefreshError(err.message)
    }
  }

  // A 409 means the IDR was submitted elsewhere: say so, then reload the saved report read-only
  const reloadAfterConflict = async () => {
    setConflictMessage(SUBMITTED_MID_EDIT)
    try {
      loadForm(await getIdr(idrId))
      setRefreshError(null)
    } catch (err) {
      setRefreshError(err.message)
    }
  }

  // Saves the whole form, then refetches the IDR. Resolves true when the save succeeded; false when it failed, hit a
  // 409, or was skipped because another save was already running.
  const handleSaveDraft = async () => {
    if (savingRef.current) return false
    savingRef.current = true
    const editCountAtStart = editCountRef.current
    setSaveStatus('saving')
    let saved = false
    let conflict = false
    try {
      const report = await saveReport(idrId, reportId, formData)
      setSavedAt(report.updated_at)
      setSaveError(null)
      setSaveStatus('saved')
      if (editCountRef.current === editCountAtStart) setHasUnsavedChanges(false)
      saved = true
    } catch (err) {
      if (err.status === 409) {
        conflict = true
        setSaveStatus('idle')
      } else {
        setSaveError(err.message)
        setSaveStatus('error')
      }
    } finally {
      savingRef.current = false
    }
    if (conflict) await reloadAfterConflict()
    else if (saved) await refresh()
    return saved
  }

  // Runs a navigation (action) without losing edits: with unsaved changes it saves the draft first and only navigates
  // if that save succeeded; a failed save or 409 stays on the page, where the save error / conflict message shows.
  const navigateSafely = async (action) => {
    if (hasUnsavedChanges && !(await handleSaveDraft())) return
    await action()
  }

  // This report's own row (report_type, is_addendum, parent_report_id, ...), from the last fetch
  const report = reports.find(r => r.report_id === reportId) ?? null

  const isLocked = idrStatus !== 'draft'
  // An auto-generated General is read-only too: its content is composed from the other reports.
  const isReadOnly = isLocked || isAutoGenerated

  return {
    // Route ids, for the shell's attachments section
    idrId, projectId, reportId,

    // Form state and handlers
    formData, updateForm, handleSaveDraft,
    handleInputChange, handleNestedInputChange, handleSafetyCheckChange, handleSafetyRemarksChange,
    addPayItem, handlePayItemChange, removePayItem,
    handleAddTrade, handleChangeAdditionalWorkforce, handleRemoveAdditionalWorkforce,
    handleAddEquipment, handleChangeAdditionalEquipment, handleRemoveAdditionalEquipment,

    // Load state
    loadStatus, loadError, loadAttempt, retryLoad,

    // IDR + project state
    idr, reports, report, project, idrStatus, submittedAt,

    // The project's contract items (for the pay-item picker)
    contractItems, contractItemsLoading, contractItemsError,

    // Save state
    saveStatus, savedAt, saveError, hasUnsavedChanges,

    // Error/conflict UI state
    refreshError, conflictMessage, refresh, reloadAfterConflict,

    // Derived flags
    isLocked, isReadOnly, isAutoGenerated,

    // Navigation
    backToIdr, backToProject, navigateSafely,
  }
}
