/**
 * The layout every report page shares, driven by the object useReportForm returns: loading and load-error screens,
 * the header (Back to IDR, save status + Save Draft, or the submitted banner), conflict / refresh alerts, the project
 * card, the auto-generated banner, the IDR context line, the read-only fieldset around the page's own sections
 * (children), attachments, addendums (main reports only) and the footer buttons.
 * Props: title, form, autoGeneratedBannerText (General only), children.
 */
import { ArrowLeft, Info } from 'lucide-react'
import SaveDraftButton from '../SaveDraftButton'
import SubmittedBanner from '../SubmittedBanner'
import SaveStatusText from '../SaveStatusText'
import IdrContextLine from '../IdrContextLine'
import AttachmentsSection from '../AttachmentsSection'
import AddendumsSection from './AddendumsSection'

const SUBMITTED_LABEL = 'This report belongs to an IDR that was submitted'

export default function ReportPageShell({ title, form, autoGeneratedBannerText, children }) {
  if (form.loadStatus === 'loading') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div role="status" className="animate-spin rounded-full h-12 w-12 border-b-2 border-construction-600"></div>
      </div>
    )
  }

  if (form.loadStatus === 'error') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
        <div className="bg-white rounded-lg shadow-sm p-6 text-center max-w-md">
          <h2 className="text-lg font-bold text-gray-900 mb-2">Couldn't open this report</h2>
          <p className="text-red-600 mb-6">{form.loadError}</p>
          <div className="flex justify-center space-x-3">
            <button onClick={form.retryLoad} className="btn-primary">
              Retry
            </button>
            <button onClick={form.backToIdr} className="btn-secondary">
              Back to IDR
            </button>
          </div>
        </div>
      </div>
    )
  }

  const { project, isLocked, isReadOnly, isAutoGenerated } = form

  // Rendered in the header and the footer, hidden once the IDR is submitted
  const reportActions = (
    <SaveDraftButton onClick={form.handleSaveDraft} saving={form.saveStatus === 'saving'} />
  )

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      {/* Header */}
      <header className="bg-white shadow-sm sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <button
              onClick={form.backToIdr}
              className="flex items-center space-x-2 text-construction-700 hover:text-construction-800"
            >
              <ArrowLeft className="h-5 w-5" />
              <span className="font-medium">Back to IDR</span>
            </button>
            {isLocked ? (
              <SubmittedBanner submittedAt={form.submittedAt} label={SUBMITTED_LABEL} />
            ) : isAutoGenerated ? null : (
              <div className="flex items-center space-x-3">
                <SaveStatusText
                  status={form.saveStatus}
                  savedAt={form.savedAt}
                  error={form.saveError}
                  hasUnsavedChanges={form.hasUnsavedChanges}
                />
                {reportActions}
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        {form.conflictMessage && (
          <div role="alert" className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-4 mb-6">
            {form.conflictMessage}
          </div>
        )}

        {form.refreshError && (
          <div role="alert" className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-4 mb-6 flex items-center justify-between">
            <span>Couldn't refresh this IDR: {form.refreshError}</span>
            <button onClick={form.conflictMessage ? form.reloadAfterConflict : form.refresh} className="btn-secondary">
              Retry
            </button>
          </div>
        )}
        {/* Project Info Header */}
        <div className="bg-white rounded-lg shadow-sm p-6 mb-6">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">{title}</h1>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            <div>
              <p><span className="font-medium text-construction-700">Contract No:</span> {project.project_id}</p>
              <p><span className="font-medium text-construction-700">Reg. No:</span> {project.registration_code}</p>
              <p><span className="font-medium text-construction-700">Project Description:</span> {project.project_description}</p>
            </div>
            <div>
              <p><span className="font-medium text-construction-700">Borough:</span> {project.borough}</p>
            </div>
          </div>
        </div>

        {isAutoGenerated && !isLocked && autoGeneratedBannerText && (
          <div className="flex items-start space-x-2 bg-blue-50 border border-blue-200 text-blue-800 rounded-lg p-4 mb-6 text-sm">
            <Info className="h-5 w-5 flex-shrink-0 mt-0.5" />
            <span>{autoGeneratedBannerText}</span>
          </div>
        )}

        <IdrContextLine idr={form.idr} />

        {/* The whole form is read-only once the IDR is submitted or the report is auto-generated */}
        <fieldset disabled={isReadOnly} className="min-w-0 border-0 p-0 m-0">
          {children}
        </fieldset>

        {/* Outside the fieldset so View still works on a submitted IDR; an auto-generated General has no attachments */}
        {!isAutoGenerated && (
          <AttachmentsSection idrId={form.idrId} reportId={form.reportId} isSubmitted={isLocked} className="mb-6" />
        )}

        {/* Only a main report takes addendums; add / delete are off once submitted or on an auto-generated General */}
        {!form.report?.is_addendum && (
          <AddendumsSection
            projectId={form.projectId}
            idrId={form.idrId}
            reportId={form.reportId}
            reports={form.reports}
            onChanged={form.refresh}
            disabled={isReadOnly}
          />
        )}

        {/* Action Buttons */}
        <div className="flex justify-between items-center">
          <button
            onClick={form.backToProject}
            className="btn-secondary"
          >
            Cancel
          </button>
          {!isReadOnly && <div className="flex space-x-3">{reportActions}</div>}
        </div>
      </main>
    </div>
  )
}
