// Hardcoded dev user — placeholder until real auth (Phase D-1).
// Everything auth-fake lives here and in services/session.js, so replacing it is two deletes.
import { CURRENT_USER_ID, CURRENT_USER_NAME } from '../services/session'

// Genghis Khan's uuid in the live ICID database (generated by the DB, not by seed.sql)
export const GENGHIS_UUID = CURRENT_USER_ID

export const DEV_USER = {
  id: GENGHIS_UUID,
  email: 'KhanG@magnoleng.pc',
  user_metadata: {
    full_name: CURRENT_USER_NAME,
    role: 'inspector'
  }
}
