// Hardcoded dev user — placeholder until real auth (Phase D-1).
// Everything auth-fake lives here so replacing it is a single delete.

// Genghis Khan's uuid in the live ICID database (generated by the DB, not by seed.sql)
export const GENGHIS_UUID = '327d3ed2-a3d6-4235-9408-7fe721b12bed'

export const DEV_USER = {
  id: GENGHIS_UUID,
  email: 'KhanG@magnoleng.pc',
  user_metadata: {
    full_name: 'Genghis Khan',
    role: 'inspector'
  }
}
