/**
 * General report inside an IDR, at /project/:projectId/idr/:idrId/general/:reportId.
 * Loads the parent IDR, uses this report's report_data as the form (report-specific fields only; the IDR's date,
 * times and weather show as a read-only context line), and Save Draft PUTs the whole form back
 * and then silently refetches the IDR. Submitting happens on the IDR page; once the IDR is submitted
 * (including mid-edit, detected by a 409 on save) the form renders read-only with a banner.
 * An auto-generated General is read-only too, with its own banner. Load / save / layout: useReportForm + ReportPageShell.
 */
import { useParams } from 'react-router-dom'
import useReportForm from '../../lib/useReportForm'
import { formDataFromReportData, sharedSectionDefaults } from '../../lib/reportData'
import ReportPageShell from '../../components/reports/ReportPageShell'
import DescriptionSection from '../../components/reports/DescriptionSection'
import PayItemsSection from '../../components/reports/PayItemsSection'
import WorkforceEquipmentCard from '../../components/reports/WorkforceEquipmentCard'
import SafetyChecklistSection from '../../components/reports/SafetyChecklistSection'
import CommentsSection from '../../components/reports/CommentsSection'

const AUTO_GENERATED_BANNER =
  'This General is auto-generated from your other reports. To change what appears here, edit the individual reports.'
const DESCRIPTION_SUBHEADING =
  'Specify for Each Operation: Item No., Subcontractor (if any), Location, Nature of Work, Results and Details.'

// A blank General report. Only report-specific fields: date, times and weather come from the IDR.
function emptyFormData() {
  return {
    description: '',
    ...sharedSectionDefaults()
  }
}

export default function GeneralReportPage() {
  const { projectId, idrId, reportId } = useParams()
  const form = useReportForm({
    idrId,
    projectId,
    reportId,
    expectedReportType: 'GEN',
    emptyFormData,
    formDataFromReport: formDataFromReportData,
    isAutoGenType: true,
  })
  const { formData, isReadOnly } = form

  return (
    <ReportPageShell title="General Inspector's Report" autoGeneratedBannerText={AUTO_GENERATED_BANNER} form={form}>
      <DescriptionSection
        value={formData.description}
        onChange={(value) => form.handleInputChange('description', value)}
        subheading={DESCRIPTION_SUBHEADING}
        disabled={isReadOnly}
      />

      {/* Pay Items */}
      <PayItemsSection
        payItems={formData.payItems}
        onAddItem={form.addPayItem}
        onItemChange={form.handlePayItemChange}
        disabled={isReadOnly}
      />

      {/* Workforce and Equipment */}
      <WorkforceEquipmentCard form={form} />

      {/* Safety Checks */}
      <SafetyChecklistSection
        safetyChecks={formData.safetyChecks}
        onChange={form.handleSafetyCheckChange}
        remarks={formData.safetyRemarks}
        onRemarksChange={form.handleSafetyRemarksChange}
        disabled={isReadOnly}
      />

      {/* Comments */}
      <CommentsSection value={formData.comments} onChange={(v) => form.handleInputChange('comments', v)} disabled={isReadOnly} />
    </ReportPageShell>
  )
}
