import { describe, it, expect, vi, beforeEach } from 'vitest'
import { renderHook, act, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import useReportForm, { SUBMITTED_MID_EDIT } from '../useReportForm'
import * as api from '../../services/api'

vi.mock('../../services/api', () => ({
  getIdr: vi.fn(),
  getProjectById: vi.fn(),
  saveReport: vi.fn(),
}))

const IDR_ID = 'idr-1'
const REPORT_ID = 'rep-1'
const PROJECT = { project_id: 'HWS0023', registration_code: '2024123457', project_description: 'Curbs', borough: 'Queens' }

function idrWith({ reportType = 'GEN', reportData = { description: 'Poured curb' }, isAutoGenerated = false, ...overrides } = {}) {
  return {
    idr_id: IDR_ID,
    project_id: 'HWS0023',
    status: 'draft',
    submitted_at: null,
    reports: [{ report_id: REPORT_ID, report_type: reportType, report_data: reportData, is_auto_generated: isAutoGenerated }],
    ...overrides,
  }
}

// A minimal page config: a one-field form whose loader keeps only description
const emptyFormData = () => ({ description: '', payItems: [] })
const formDataFromReport = (reportData, defaults) => ({ ...defaults, ...reportData })

function renderForm(options = {}) {
  return renderHook(() => useReportForm({
    idrId: IDR_ID,
    projectId: 'HWS0023',
    reportId: REPORT_ID,
    expectedReportType: 'GEN',
    emptyFormData,
    formDataFromReport,
    ...options,
  }), { wrapper: ({ children }) => <MemoryRouter>{children}</MemoryRouter> })
}

const ready = (result) => waitFor(() => expect(result.current.loadStatus).toBe('ready'))

beforeEach(() => {
  vi.clearAllMocks()
  api.getIdr.mockResolvedValue(idrWith())
  api.getProjectById.mockResolvedValue(PROJECT)
  api.saveReport.mockImplementation(async (_, reportId, reportData) => ({
    report_id: reportId, report_data: reportData, updated_at: '2026-09-25T14:05:00Z',
  }))
})

describe('useReportForm — loading', () => {
  it('starts loading with the blank form', () => {
    api.getIdr.mockReturnValue(new Promise(() => {}))
    const { result } = renderForm()
    expect(result.current.loadStatus).toBe('loading')
    expect(result.current.formData).toEqual({ description: '', payItems: [] })
  })

  it('loads the IDR and project, and fills the form through formDataFromReport with the blank defaults', async () => {
    const loader = vi.fn(formDataFromReport)
    const { result } = renderForm({ formDataFromReport: loader })
    await ready(result)
    expect(api.getIdr).toHaveBeenCalledWith(IDR_ID)
    expect(api.getProjectById).toHaveBeenCalledWith('HWS0023')
    expect(loader).toHaveBeenCalledWith({ description: 'Poured curb' }, { description: '', payItems: [] })
    expect(result.current.formData).toEqual({ description: 'Poured curb', payItems: [] })
    expect(result.current.project).toEqual(PROJECT)
    expect(result.current.idr).not.toHaveProperty('reports')
    expect(result.current.hasUnsavedChanges).toBe(false)
    expect(result.current.isReadOnly).toBe(false)
  })

  it('reports a load failure, and retryLoad loads again', async () => {
    api.getIdr.mockRejectedValueOnce(new Error('IDR not found'))
    const { result } = renderForm()
    await waitFor(() => expect(result.current.loadStatus).toBe('error'))
    expect(result.current.loadError).toBe('IDR not found')

    act(() => result.current.retryLoad())
    await ready(result)
    expect(api.getIdr).toHaveBeenCalledTimes(2)
  })

  it.each([
    ['the report is another type', idrWith({ reportType: 'SWR' }), 'This report is not a General report'],
    ['the report is not in the IDR', idrWith({ reports: [] }), 'Report not found in this IDR'],
    ['the IDR is in another project', idrWith({ project_id: 'OTHER' }), 'IDR not found in this project'],
  ])('fails to load when %s', async (_, idr, message) => {
    api.getIdr.mockResolvedValue(idr)
    const { result } = renderForm()
    await waitFor(() => expect(result.current.loadStatus).toBe('error'))
    expect(result.current.loadError).toBe(message)
  })

  it('does not reload when the page passes new function instances on every render', async () => {
    const { result, rerender } = renderHook(() => useReportForm({
      idrId: IDR_ID,
      projectId: 'HWS0023',
      reportId: REPORT_ID,
      expectedReportType: 'GEN',
      emptyFormData: () => ({ description: '', payItems: [] }),
      formDataFromReport: (reportData, defaults) => ({ ...defaults, ...reportData }),
    }), { wrapper: ({ children }) => <MemoryRouter>{children}</MemoryRouter> })
    await ready(result)
    rerender()
    rerender()
    expect(api.getIdr).toHaveBeenCalledTimes(1)
  })

  it("names the expected type's label in the mismatch error", async () => {
    const { result } = renderForm({ expectedReportType: 'SWCB' })
    await waitFor(() => expect(result.current.loadStatus).toBe('error'))
    expect(result.current.loadError).toBe('This report is not a Sidewalk, Curb, Concrete Base report')
  })
})

describe('useReportForm — auto-generated and read-only', () => {
  it('reads is_auto_generated only for an auto-gen type, and makes the form read-only', async () => {
    api.getIdr.mockResolvedValue(idrWith({ isAutoGenerated: true }))
    const { result } = renderForm({ isAutoGenType: true })
    await ready(result)
    expect(result.current.isAutoGenerated).toBe(true)
    expect(result.current.isLocked).toBe(false)
    expect(result.current.isReadOnly).toBe(true)
  })

  it('ignores is_auto_generated for other types', async () => {
    api.getIdr.mockResolvedValue(idrWith({ isAutoGenerated: true }))
    const { result } = renderForm()
    await ready(result)
    expect(result.current.isAutoGenerated).toBe(false)
    expect(result.current.isReadOnly).toBe(false)
  })

  it('is locked and read-only when the IDR is submitted', async () => {
    api.getIdr.mockResolvedValue(idrWith({ status: 'submitted', submitted_at: '2026-09-25T15:10:00Z' }))
    const { result } = renderForm()
    await ready(result)
    expect(result.current.isLocked).toBe(true)
    expect(result.current.isReadOnly).toBe(true)
    expect(result.current.submittedAt).toBe('2026-09-25T15:10:00Z')
  })
})

describe('useReportForm — editing and saving', () => {
  it('marks edits as unsaved, saves the whole form, then refetches the IDR', async () => {
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'Poured curb - day 2'))
    act(() => result.current.addPayItem())
    expect(result.current.hasUnsavedChanges).toBe(true)

    await act(() => result.current.handleSaveDraft())
    expect(api.saveReport).toHaveBeenCalledWith(IDR_ID, REPORT_ID, {
      description: 'Poured curb - day 2',
      payItems: [{ itemNo: '', budgetCode: '', payQuantity: '', description: '' }],
    })
    expect(result.current.saveStatus).toBe('saved')
    expect(result.current.savedAt).toBe('2026-09-25T14:05:00Z')
    expect(result.current.hasUnsavedChanges).toBe(false)
    expect(api.getIdr).toHaveBeenCalledTimes(2)
  })

  it('keeps the typed data and reports the error when a save fails', async () => {
    api.saveReport.mockRejectedValueOnce(new Error('Network error'))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'keep me'))
    await act(() => result.current.handleSaveDraft())
    expect(result.current.saveStatus).toBe('error')
    expect(result.current.saveError).toBe('Network error')
    expect(result.current.formData.description).toBe('keep me')
    expect(result.current.hasUnsavedChanges).toBe(true)
    expect(api.getIdr).toHaveBeenCalledTimes(1) // no refetch after a failed save
  })

  it('on a 409 says so and reloads the saved report read-only', async () => {
    api.getIdr
      .mockResolvedValueOnce(idrWith())
      .mockResolvedValue(idrWith({ status: 'submitted', submitted_at: '2026-09-25T15:10:00Z' }))
    api.saveReport.mockRejectedValueOnce(Object.assign(new Error('Only draft IDRs can be edited'), { status: 409 }))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'unsaved'))
    await act(() => result.current.handleSaveDraft())

    expect(result.current.conflictMessage).toBe(SUBMITTED_MID_EDIT)
    expect(result.current.formData.description).toBe('Poured curb')
    expect(result.current.isReadOnly).toBe(true)
    expect(result.current.hasUnsavedChanges).toBe(false)
    expect(result.current.saveStatus).toBe('idle')
  })

  it('reports a failed refetch after a save, and refresh() clears it', async () => {
    const { result } = renderForm()
    await ready(result)
    api.getIdr.mockRejectedValueOnce(new Error('Refresh failed'))
    await act(() => result.current.handleSaveDraft())
    expect(result.current.refreshError).toBe('Refresh failed')

    await act(() => result.current.refresh())
    expect(result.current.refreshError).toBeNull()
  })
})
