import { describe, it, expect, vi, beforeEach } from 'vitest'
import { renderHook, act, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import useReportForm, { SUBMITTED_MID_EDIT } from '../useReportForm'
import { formDataFromReportData, sharedSectionDefaults } from '../reportData'
import * as api from '../../services/api'
import { MOCK_CONTRACT_ITEMS } from '../../test/contractItems'

vi.mock('../../services/api', () => ({
  getContractItems: vi.fn(),
  getIdr: vi.fn(),
  getProjectById: vi.fn(),
  saveReport: vi.fn(),
}))

const IDR_ID = 'idr-1'
const REPORT_ID = 'rep-1'
const PROJECT = { project_id: 'HWS0023', registration_code: '2024123457', project_description: 'Curbs', borough: 'Queens' }

function idrWith({ reportType = 'GEN', reportData = { description: 'Poured curb' }, isAutoGenerated = false, ...overrides } = {}) {
  return {
    idr_id: IDR_ID,
    project_id: 'HWS0023',
    status: 'draft',
    submitted_at: null,
    reports: [{ report_id: REPORT_ID, report_type: reportType, report_data: reportData, is_auto_generated: isAutoGenerated }],
    ...overrides,
  }
}

// A minimal page config: a one-field form whose loader keeps only description
const emptyFormData = () => ({ description: '', payItems: [] })
const formDataFromReport = (reportData, defaults) => ({ ...defaults, ...reportData })

function renderForm(options = {}) {
  return renderHook(() => useReportForm({
    idrId: IDR_ID,
    projectId: 'HWS0023',
    reportId: REPORT_ID,
    expectedReportType: 'GEN',
    emptyFormData,
    formDataFromReport,
    ...options,
  }), { wrapper: ({ children }) => <MemoryRouter>{children}</MemoryRouter> })
}

const ready = (result) => waitFor(() => expect(result.current.loadStatus).toBe('ready'))

beforeEach(() => {
  vi.clearAllMocks()
  api.getIdr.mockResolvedValue(idrWith())
  api.getProjectById.mockResolvedValue(PROJECT)
  api.getContractItems.mockResolvedValue(MOCK_CONTRACT_ITEMS)
  api.saveReport.mockImplementation(async (_, reportId, reportData) => ({
    report_id: reportId, report_data: reportData, updated_at: '2026-09-25T14:05:00Z',
  }))
})

describe('useReportForm — loading', () => {
  it('starts loading with the blank form', () => {
    api.getIdr.mockReturnValue(new Promise(() => {}))
    const { result } = renderForm()
    expect(result.current.loadStatus).toBe('loading')
    expect(result.current.formData).toEqual({ description: '', payItems: [] })
  })

  it('loads the IDR and project, and fills the form through formDataFromReport with the blank defaults', async () => {
    const loader = vi.fn(formDataFromReport)
    const { result } = renderForm({ formDataFromReport: loader })
    await ready(result)
    expect(api.getIdr).toHaveBeenCalledWith(IDR_ID)
    expect(api.getProjectById).toHaveBeenCalledWith('HWS0023')
    expect(loader).toHaveBeenCalledWith({ description: 'Poured curb' }, { description: '', payItems: [] })
    expect(result.current.formData).toEqual({ description: 'Poured curb', payItems: [] })
    expect(result.current.project).toEqual(PROJECT)
    expect(result.current.idr).not.toHaveProperty('reports')
    expect(result.current.hasUnsavedChanges).toBe(false)
    expect(result.current.isReadOnly).toBe(false)
  })

  it('reports a load failure, and retryLoad loads again', async () => {
    api.getIdr.mockRejectedValueOnce(new Error('IDR not found'))
    const { result } = renderForm()
    await waitFor(() => expect(result.current.loadStatus).toBe('error'))
    expect(result.current.loadError).toBe('IDR not found')

    act(() => result.current.retryLoad())
    await ready(result)
    expect(api.getIdr).toHaveBeenCalledTimes(2)
  })

  it.each([
    ['the report is another type', idrWith({ reportType: 'SWR' }), 'This report is not a General report'],
    ['the report is not in the IDR', idrWith({ reports: [] }), 'Report not found in this IDR'],
    ['the IDR is in another project', idrWith({ project_id: 'OTHER' }), 'IDR not found in this project'],
  ])('fails to load when %s', async (_, idr, message) => {
    api.getIdr.mockResolvedValue(idr)
    const { result } = renderForm()
    await waitFor(() => expect(result.current.loadStatus).toBe('error'))
    expect(result.current.loadError).toBe(message)
  })

  it('does not reload when the page passes new function instances on every render', async () => {
    const { result, rerender } = renderHook(() => useReportForm({
      idrId: IDR_ID,
      projectId: 'HWS0023',
      reportId: REPORT_ID,
      expectedReportType: 'GEN',
      emptyFormData: () => ({ description: '', payItems: [] }),
      formDataFromReport: (reportData, defaults) => ({ ...defaults, ...reportData }),
    }), { wrapper: ({ children }) => <MemoryRouter>{children}</MemoryRouter> })
    await ready(result)
    rerender()
    rerender()
    expect(api.getIdr).toHaveBeenCalledTimes(1)
  })

  it("names the expected type's label in the mismatch error", async () => {
    const { result } = renderForm({ expectedReportType: 'SWCB' })
    await waitFor(() => expect(result.current.loadStatus).toBe('error'))
    expect(result.current.loadError).toBe('This report is not a Sidewalk, Curb, Concrete Base report')
  })
})

describe('useReportForm — navigateSafely', () => {
  it('navigates straight away when there are no unsaved changes', async () => {
    const { result } = renderForm()
    await ready(result)
    const action = vi.fn()
    await act(() => result.current.navigateSafely(action))
    expect(action).toHaveBeenCalledTimes(1)
    expect(api.saveReport).not.toHaveBeenCalled()
  })

  it('saves unsaved changes first, then navigates', async () => {
    const order = []
    api.saveReport.mockImplementation(async (_, reportId, reportData) => {
      order.push('save')
      return { report_id: reportId, report_data: reportData, updated_at: '2026-09-25T14:05:00Z' }
    })
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'edited'))
    await act(() => result.current.navigateSafely(async () => { order.push('navigate') }))

    expect(api.saveReport).toHaveBeenCalledWith(IDR_ID, REPORT_ID, { description: 'edited', payItems: [] })
    expect(order).toEqual(['save', 'navigate'])
  })

  it('stays put when the save fails, with the save error set', async () => {
    api.saveReport.mockRejectedValueOnce(new Error('Network error'))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'edited'))
    const action = vi.fn()
    await act(() => result.current.navigateSafely(action))

    expect(action).not.toHaveBeenCalled()
    expect(result.current.saveError).toBe('Network error')
    expect(result.current.hasUnsavedChanges).toBe(true)
  })

  it('stays put on a 409, with the conflict message set', async () => {
    api.getIdr
      .mockResolvedValueOnce(idrWith())
      .mockResolvedValue(idrWith({ status: 'submitted', submitted_at: '2026-09-25T15:10:00Z' }))
    api.saveReport.mockRejectedValueOnce(Object.assign(new Error('Only draft IDRs can be edited'), { status: 409 }))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'edited'))
    const action = vi.fn()
    await act(() => result.current.navigateSafely(action))

    expect(action).not.toHaveBeenCalled()
    expect(result.current.conflictMessage).toBe(SUBMITTED_MID_EDIT)
  })

  it('does not navigate (or save twice) while a save is already running', async () => {
    let finishSave
    api.saveReport.mockImplementationOnce((_, reportId, reportData) => new Promise(resolve => {
      finishSave = () => resolve({ report_id: reportId, report_data: reportData, updated_at: '2026-09-25T14:05:00Z' })
    }))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'edited'))

    let firstSave
    act(() => { firstSave = result.current.handleSaveDraft() })
    const action = vi.fn()
    await act(() => result.current.navigateSafely(action))
    expect(action).not.toHaveBeenCalled()
    expect(api.saveReport).toHaveBeenCalledTimes(1)

    await act(async () => { finishSave(); await firstSave })
    expect(result.current.hasUnsavedChanges).toBe(false)
  })
})

describe("useReportForm — the IDR's reports", () => {
  const main = { report_id: REPORT_ID, report_type: 'GEN', report_data: {}, is_addendum: false, parent_report_id: null }
  const addendum = { report_id: 'rep-2', report_type: 'CONC_MIX', report_data: {}, is_addendum: true, parent_report_id: REPORT_ID }

  it("exposes every report in the IDR and this report's own row", async () => {
    api.getIdr.mockResolvedValue(idrWith({ reports: [main, addendum] }))
    const { result } = renderForm()
    await ready(result)
    expect(result.current.reports).toEqual([main, addendum])
    expect(result.current.report).toEqual(main)
  })

  it('refresh() refetches the IDR and updates the reports without touching the form', async () => {
    api.getIdr.mockResolvedValueOnce(idrWith({ reports: [{ ...main, report_data: { description: 'Poured curb' } }, addendum] }))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'typing'))

    api.getIdr.mockResolvedValueOnce(idrWith({ reports: [{ ...main, report_data: { description: 'Poured curb' } }] }))
    await act(() => result.current.refresh())
    expect(api.getIdr).toHaveBeenCalledTimes(2)
    expect(result.current.reports).toHaveLength(1)
    expect(result.current.formData.description).toBe('typing')
  })
})

describe('useReportForm — auto-generated and read-only', () => {
  it('reads is_auto_generated only for an auto-gen type, and makes the form read-only', async () => {
    api.getIdr.mockResolvedValue(idrWith({ isAutoGenerated: true }))
    const { result } = renderForm({ isAutoGenType: true })
    await ready(result)
    expect(result.current.isAutoGenerated).toBe(true)
    expect(result.current.isLocked).toBe(false)
    expect(result.current.isReadOnly).toBe(true)
  })

  it('ignores is_auto_generated for other types', async () => {
    api.getIdr.mockResolvedValue(idrWith({ isAutoGenerated: true }))
    const { result } = renderForm()
    await ready(result)
    expect(result.current.isAutoGenerated).toBe(false)
    expect(result.current.isReadOnly).toBe(false)
  })

  it('is locked and read-only when the IDR is submitted', async () => {
    api.getIdr.mockResolvedValue(idrWith({ status: 'submitted', submitted_at: '2026-09-25T15:10:00Z' }))
    const { result } = renderForm()
    await ready(result)
    expect(result.current.isLocked).toBe(true)
    expect(result.current.isReadOnly).toBe(true)
    expect(result.current.submittedAt).toBe('2026-09-25T15:10:00Z')
  })
})

describe('useReportForm — editing and saving', () => {
  it('marks edits as unsaved, saves the whole form, then refetches the IDR', async () => {
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'Poured curb - day 2'))
    act(() => result.current.addPayItem())
    expect(result.current.hasUnsavedChanges).toBe(true)

    await act(() => result.current.handleSaveDraft())
    expect(api.saveReport).toHaveBeenCalledWith(IDR_ID, REPORT_ID, {
      description: 'Poured curb - day 2',
      payItems: [{ itemNo: '', budgetCode: '', payQuantity: '', unit: '', description: '' }],
    })
    expect(result.current.saveStatus).toBe('saved')
    expect(result.current.savedAt).toBe('2026-09-25T14:05:00Z')
    expect(result.current.hasUnsavedChanges).toBe(false)
    expect(api.getIdr).toHaveBeenCalledTimes(2)
  })

  it('keeps the typed data and reports the error when a save fails', async () => {
    api.saveReport.mockRejectedValueOnce(new Error('Network error'))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'keep me'))
    await act(() => result.current.handleSaveDraft())
    expect(result.current.saveStatus).toBe('error')
    expect(result.current.saveError).toBe('Network error')
    expect(result.current.formData.description).toBe('keep me')
    expect(result.current.hasUnsavedChanges).toBe(true)
    expect(api.getIdr).toHaveBeenCalledTimes(1) // no refetch after a failed save
  })

  it('on a 409 says so and reloads the saved report read-only', async () => {
    api.getIdr
      .mockResolvedValueOnce(idrWith())
      .mockResolvedValue(idrWith({ status: 'submitted', submitted_at: '2026-09-25T15:10:00Z' }))
    api.saveReport.mockRejectedValueOnce(Object.assign(new Error('Only draft IDRs can be edited'), { status: 409 }))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.handleInputChange('description', 'unsaved'))
    await act(() => result.current.handleSaveDraft())

    expect(result.current.conflictMessage).toBe(SUBMITTED_MID_EDIT)
    expect(result.current.formData.description).toBe('Poured curb')
    expect(result.current.isReadOnly).toBe(true)
    expect(result.current.hasUnsavedChanges).toBe(false)
    expect(result.current.saveStatus).toBe('idle')
  })

  it('handleSaveDraft resolves true on success and false on failure', async () => {
    const { result } = renderForm()
    await ready(result)
    let saved
    await act(async () => { saved = await result.current.handleSaveDraft() })
    expect(saved).toBe(true)

    api.saveReport.mockRejectedValueOnce(new Error('Network error'))
    await act(async () => { saved = await result.current.handleSaveDraft() })
    expect(saved).toBe(false)
  })

  it('reports a failed refetch after a save, and refresh() clears it', async () => {
    const { result } = renderForm()
    await ready(result)
    api.getIdr.mockRejectedValueOnce(new Error('Refresh failed'))
    await act(() => result.current.handleSaveDraft())
    expect(result.current.refreshError).toBe('Refresh failed')

    await act(() => result.current.refresh())
    expect(result.current.refreshError).toBeNull()
  })
})

describe('useReportForm — pay item unit', () => {
  // The real loader every report page uses, over the shared sections' blank state
  const realLoader = { emptyFormData: sharedSectionDefaults, formDataFromReport: formDataFromReportData }

  it("addPayItem's blank row has an empty unit", async () => {
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.addPayItem())
    expect(result.current.formData.payItems).toEqual([
      { itemNo: '', budgetCode: '', payQuantity: '', unit: '', description: '' },
    ])
  })

  it('keeps a saved unit on load', async () => {
    const payItem = { itemNo: '4.13 AAS', budgetCode: '12345', payQuantity: '150.00', unit: 'SF', description: 'Sidewalk' }
    api.getIdr.mockResolvedValue(idrWith({ reportData: { payItems: [payItem] } }))
    const { result } = renderForm(realLoader)
    await ready(result)
    expect(result.current.formData.payItems).toEqual([payItem])
  })

  it('gives pay items saved before the unit field an empty unit', async () => {
    api.getIdr.mockResolvedValue(idrWith({
      reportData: { payItems: [{ itemNo: '4.01', budgetCode: 'B7', payQuantity: '12', description: 'Curb' }] },
    }))
    const { result } = renderForm(realLoader)
    await ready(result)
    expect(result.current.formData.payItems).toEqual([
      { itemNo: '4.01', budgetCode: 'B7', payQuantity: '12', unit: '', description: 'Curb' },
    ])
  })

  it('turns a saved null unit into an empty one', async () => {
    api.getIdr.mockResolvedValue(idrWith({
      reportData: { payItems: [{ itemNo: '4.01', budgetCode: '', payQuantity: '', unit: null, description: '' }] },
    }))
    const { result } = renderForm(realLoader)
    await ready(result)
    expect(result.current.formData.payItems[0].unit).toBe('')
  })
})

describe('useReportForm — removePayItem', () => {
  it('removes the pay item at that index and marks the form unsaved', async () => {
    api.getIdr.mockResolvedValue(idrWith({ reportData: { payItems: [{ itemNo: 'A' }, { itemNo: 'B' }] } }))
    const { result } = renderForm()
    await ready(result)
    act(() => result.current.removePayItem(0))
    expect(result.current.formData.payItems).toEqual([{ itemNo: 'B' }])
    expect(result.current.hasUnsavedChanges).toBe(true)
  })
})

describe('useReportForm — contract items', () => {
  it("fetches the project's contract items once and exposes them", async () => {
    const { result } = renderForm()
    expect(result.current.contractItemsLoading).toBe(true)
    await waitFor(() => expect(result.current.contractItemsLoading).toBe(false))
    expect(api.getContractItems).toHaveBeenCalledWith('HWS0023')
    expect(result.current.contractItems).toEqual(MOCK_CONTRACT_ITEMS)
    expect(result.current.contractItemsError).toBeNull()

    // Saving refetches the IDR but not the contract items
    await ready(result)
    await act(() => result.current.handleSaveDraft())
    expect(api.getContractItems).toHaveBeenCalledTimes(1)
  })

  it('records a failed fetch without blocking the form', async () => {
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {})
    api.getContractItems.mockRejectedValueOnce(new Error('Failed to fetch contract items'))
    const { result } = renderForm()
    await waitFor(() => expect(result.current.contractItemsLoading).toBe(false))
    await ready(result)
    expect(result.current.contractItemsError).toBe('Failed to fetch contract items')
    expect(result.current.contractItems).toEqual([])
    expect(result.current.formData.description).toBe('Poured curb')
    expect(consoleError).toHaveBeenCalled()
    consoleError.mockRestore()
  })
})
